// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";

import './App.css'
;

var logo = (require('./logo.svg'));

function App(Props) {
  return React.createElement("div", {
              className: "App"
            }, React.createElement("header", {
                  className: "App-header"
                }, React.createElement("img", {
                      className: "App-logo",
                      alt: "logo",
                      src: logo
                    }), React.createElement("p", undefined, "Edit ", React.createElement("code", undefined, "src/App.re"), " and save to reload."), React.createElement("a", {
                      className: "App-link",
                      href: "https://reasonml.github.io/reason-react",
                      rel: "noopener noreferrer",
                      target: "_blank"
                    }, "Learn Reason React")));
}

var make = App;

export {
  logo ,
  make ,
  
}
/*  Not a pure module */
