// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as ServiceWorker from "./serviceWorker";
import * as App$HasuraReasonDemoApp from "./App.js";

import './index.css'
;

function register_service_worker(prim) {
  ServiceWorker.register();
  return /* () */0;
}

function unregister_service_worker(prim) {
  ServiceWorker.unregister();
  return /* () */0;
}

ReactDOMRe.renderToElementWithId(React.createElement(App$HasuraReasonDemoApp.make, { }), "root");

ServiceWorker.unregister();

export {
  register_service_worker ,
  unregister_service_worker ,
  
}
/*  Not a pure module */
